spring:
  application:
    name: API Simples de Clientes
  datasource:
    url: jdbc:h2:mem:clientes
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console